# MySQL configuration
mysql-user : cointipbot
mysql-pass : randompass1234
mysql-host : localhost
mysql-port : 3306
mysql-db: cointipbot

# Reddit configuration
reddit-username : mycointipbotuser
reddit-pass : randompass1234
reddit-useragent : /u/mycointipbotuser
reddit-botsubreddit : mycointipbotsubreddit

# Other configuration
admin-email : admin@example.com

# Cryptocoins
cc:
  bitcoin:
    enabled: false
  litecoin:
    enabled: true
    unit: ltc
    name: litecoin
    conf-file: '~/.litecoin/litecoin.conf'
    regex:
      address: '(L[1-9a-z]{20,40})'
      units: '(ltc|litecoin|litecoins)'
  ppcoin:
    enabled: false
    unit: ppc
    name: ppcoin
    conf-file: '~/.ppcoin/ppcoin.conf'
    regex:
      address: '(P[1-9a-z]{20,40})'
      units: '(ppc|ppcoin|ppcoins)'
