# MySQL
mysql:
  user: mysqluser
  pass: mysqlpass
  host: localhost
  port: 3306
  db: mysqldb

# Reddit
reddit:
  user: mybotuser
  pass: mybotpass
  batch-limit: 1000
  useragent: /u/mybotuser
  scan:
    my-subreddits: false
    these-subreddits: ["all"]
    ignore-subreddits: ["test"]
  help-url: http://www.reddit.com/r/mybotuser/wiki/index
  comments:
    verify: true
    pending: false
    expired: false
    declined: false

# Other
misc:
  qr-service-url: 'https://chart.googleapis.com/chart?cht=qr&choe=UTF-8&chs=300x300&chl='
  sleep-seconds: 30
  expire-pending-hours: 48
  subtract-txfee: false
  exchange: vircurex

# Regex
regex:
  amount:
    num: '([0-9]{1,9}(?:\.[0-9]{0,8})?)'
    keyword: '(all|flip|roll|upvote|pi|e|leet|quarter|half|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)'
  keywords:
    givetip: '(/u/mybotuser|mybotuser)'
    info: '(info)'
    register: '(register)'
    accept: '(accept)'
    decline: '(decline)'
    withdraw: '(withdraw)'
    history: '(history)'

# Amount keywords
kw:
   all: "float( self._FROM_USER.get_balance(coin=self._COIN, kind=('withdraw' if bool(self._TO_ADDR) else 'givetip')) - (self._CTB._config['cc'][self._COIN]['txfee'] if bool(self._TO_ADDR) and not self._CTB._config['misc']['subtract-txfee'] else 0.0) ) if self._FROM_USER.is_registered() and bool(self._COIN) else None"
   flip: "float( (self._CTB._config['cc'][self._COIN]['txmin']['givetip'] if bool(self._COIN) else 0.01) * float(randint(1,2)) )"
   roll: "float( (self._CTB._config['cc'][self._COIN]['txmin']['givetip'] if bool(self._COIN) else 0.01) * float(randint(1,6)) )"
   upvote: 0.1
   pi: 3.14159265
   e: 2.7182818
   leet: 1.337
   quarter: 0.25
   half: 0.5
   one: 1.0
   two: 2.0
   three: 3.0
   four: 4.0
   five: 5.0
   six: 6.0
   seven: 7.0
   eight: 8.0
   nine: 9.0
   ten: 10.0
   eleven: 11.0
   twelve: 12.0

# Logging
logging:
  info-log-filename: ctb-info.log
  debug-log-filename: ctb-debug.log

# Fiat
fiat:
  # USD
  usd:
    enabled: true
    unit: usd
    symbol: '$'
    name: US Dollar
    regex:
      units: (\$|usd)
  # EUR
  eur:
    enabled: true
    unit: eur
    symbol: '€'
    name: Euro
    regex:
      units: (€|eur)
  # GBP
  gbp:
    enabled: false
    unit: gbp
    symbol: '£'
    name: British Pound
    regex:
      units: (£|gbp)
  # JPY
  jpy:
    enabled: false
    unit: jpy
    symbol: '¥'
    name: Japanese Yen
    regex:
      units: (¥|jpy)
  # RUR
  rur:
    enabled: false
    unit: rur
    symbol: 'R'
    name: Russian Ruble
    regex:
      units: (r|rur)

# Cryptocoins
cc:
  # Bitcoin
  btc:
    enabled: false
    unit: btc
    name: Bitcoin
    conf-file: '~/.bitcoin/bitcoin.conf'
    minconf:
      givetip: 1
      withdraw: 10
    txmin:
      givetip: 0.0001
      withdraw: 0.0049
    txfee: 0.0001
    walletpassphrase: mypass1
    explorer:
      address: 'http://blockchain.info/address/'
      transaction: 'http://blockchain.info/tx/'
    regex:
      address: '([1|3][1-9a-z]{20,40})'
      units: '(btc|bitcoin|bitcoins)'
  # Litecoin
  ltc:
    enabled: false
    unit: ltc
    name: Litecoin
    conf-file: '~/.litecoin/litecoin.conf'
    minconf:
      givetip: 1
      withdraw: 10
    txmin:
      givetip: 0.01
      withdraw: 0.48
    txfee: 0.02
    walletpassphrase: mypass1
    explorer:
      address: 'http://explorer.litecoin.net/address/'
      transaction: 'http://explorer.litecoin.net/tx/'
    regex:
      address: '(L[1-9a-z]{20,40})'
      units: '(ltc|litecoin|litecoins)'
  # PPCoin
  ppc:
    enabled: false
    unit: ppc
    name: Peercoin
    conf-file: '~/.ppcoin/ppcoin.conf'
    minconf:
      givetip: 1
      withdraw: 10
    txmin:
      givetip: 0.05
      withdraw: 0.5
    txfee: 0.01
    walletpassphrase: mypass1
    explorer:
      address: 'http://www.cryptocoinexplorer.com:2750/address/'
      transaction: 'http://www.cryptocoinexplorer.com:2750/tx/'
    regex:
      address: '(P[1-9a-z]{20,40})'
      units: '(ppc|ppcoin|ppcoins|peercoin|peercoins|p2pcoin|p2pcoins)'
  # Namecoin
  nmc:
    enabled: false
    unit: nmc
    name: Namecoin
    conf-file: '~/.namecoin/bitcoin.conf'
    minconf:
      givetip: 1
      withdraw: 10
    txmin:
      givetip: 0.01
      withdraw: 0.49
    txfee: 0.01
    explorer:
      address: 'http://explorer.dot-bit.org/a/'
      transaction: 'http://explorer.dot-bit.org/tx/'
    regex:
      address: '([N|M][1-9a-z]{20,40})'
      units: '(nmc|namecoin|namecoins)'
  # Novacoin
  nvc:
    enabled: false
    unit: nvc
    name: Novacoin
    conf-file: '~/.novacoin/novacoin.conf'
    minconf:
      givetip: 1
      withdraw: 10
    txmin:
      givetip: 0.01
      withdraw: 0.49
    txfee: 0.01
    walletpassphrase: mypass1
    explorer:
      address: 'http://www.cryptocoinexplorer.com:6750/address/'
      transaction: 'http://www.cryptocoinexplorer.com:6750/tx/'
    regex:
      address: '(4[1-9a-z]{20,40})'
      units: '(nvc|novacoin|novacoins)'
  # Terracoin
  trc:
    enabled: false
    unit: trc
    name: Terracoin
    conf-file: '~/.terracoin/terracoin.conf'
    minconf:
      givetip: 1
      withdraw: 10
    txmin:
      givetip: 0.01
      withdraw: 0.49
    txfee: 0.01
    walletpassphrase: mypass1
    explorer:
      address: 'http://www.cryptocoinexplorer.com:3750/address/'
      transaction: 'http://www.cryptocoinexplorer.com:3750/tx/'
    regex:
      address: '(1[1-9a-z]{20,40})'
      units: '(trc|terracoin|terracoins)'
  # Devcoin
  dvc:
    enabled: false
    unit: dvc
    name: Devcoin
    conf-file: '~/.devcoin/devcoin.conf'
    minconf:
      givetip: 1
      withdraw: 10
    txmin:
      givetip: 1
      withdraw: 4
    txfee: 1
    explorer:
      address: 'http://glari.ch:2750/address/'
      transaction: 'http://glari.ch:2750/tx/'
    regex:
      address: '(1[1-9a-z]{20,40})'
      units: '(dvc|devcoin|devcoins)'
  # Primecoin
  xpm:
    enabled: false
    unit: xpm
    name: Primecoin
    conf-file: '~/.primecoin/primecoin.conf'
    minconf:
      givetip: 10
      withdraw: 180
    txmin:
      givetip: 0.01
      withdraw: 0.49
    txfee: 0.01
    walletpassphrase: mypass1
    explorer:
      address: 'http://primecoin.21stcenturymoneytalk.org/?addr='
      transaction: 'http://primecoin.21stcenturymoneytalk.org/?tx='
    regex:
      address: '(A[1-9a-z]{20,40})'
      units: '(xpm|primecoin|primecoins)'
﻿# -*- coding: utf-8 -*-
