# MySQL configuration
mysql-user : cointipbot
mysql-pass : randompass1234
mysql-host : localhost
mysql-port : 3306
mysql-db: cointipbot

# Reddit configuration
reddit-username : mycointipbotuser
reddit-pass : randompass1234
reddit-useragent : /u/mycointipbotuser
reddit-botsubreddit : mycointipbotsubreddit

# Other configuration
admin-email : admin@example.com

# Regex              
regex:
  amount: '([0-9]{1,7}(?:\.[0-9]{0,5})?)'

# Cryptocoins
cc:
  btc:
    enabled: false
    unit: btc
    name: bitcoin
    confile: '~/.bitcoin/bitcoin.conf'
    minconf: 2
    txmin: 0.05
    txfee: 0.0005
    walletpassphrase: mypass1
    explorer:
      address: 'http://blockchain.info/address/'
      transaction: 'http://blockchain.info/tx/'
    regex:
      address: '([1|3][1-9a-z]{20,40})'
      units: '(btc|bitcoin|bitcoins)'
  ltc:
    enabled: false
    unit: ltc
    name: litecoin
    conf-file: '~/.litecoin/litecoin.conf'
    minconf: 3
    txmin: 0.25
    txfee: 0.01
    walletpassphrase: mypass1
    explorer:
      address: 'http://explorer.litecoin.net/address/'
      transaction: 'http://explorer.litecoin.net/tx/'
    regex:
      address: '(L[1-9a-z]{20,40})'
      units: '(ltc|litecoin|litecoins)'
  ppc:
    enabled: false
    unit: ppc
    name: ppcoin
    conf-file: '~/.ppcoin/ppcoin.conf'
    minconf: 3
    txmin: 0.5
    txfee: 0.01
    walletpassphrase: mypass1
    explorer:
      address: 'http://www.cryptocoinexplorer.com:2750/address/'
      transaction: 'http://www.cryptocoinexplorer.com:2750/tx/'
    regex:
      address: '(P[1-9a-z]{20,40})'
      units: '(ppc|ppcoin|ppcoins)'

